### ISSUE TITLE
Idea: Add Timeout to simple_uart_read

### ISSUE THREAD

**Issue by andkae** [AndreRenaud/simple_uart#13]
Ho André,

for my application it would be very helpful to have a wait function in your simple_uart. Following prototype:

```c
void simple_uart_wait(struct simple_uart *sc, uint32_t wait_us)
```

This would help me to separate the platform dependent code from my independent code. Otherwise i have in my app to load some platform dependent libs to get an ```sleep``` in windows as well in linux.

Would you accept the adding of such an wait function to your code? If yes i prepare an PR.

BR,
Andreas

**Comment by AndreRenaud** [comment]
I'm not so keen on that, since it doesn't have anything to do with the UART functionality. That kind of cross-platform helper support is probably better off living in a different library/header file, especially since it's unlikely to be limited to just `sleep`.

**Comment by akaeba** [comment]
Mhh, good points. Let me ask in another way, how to ensure that i have written n-bytes to the uart after i finished the write function, or i collected n bytes after i finished the read function?

**Comment by AndreRenaud** [comment]
Yeah, that's a pretty common requirement, and unfortunately it's not super well handled at the moment. Possibly a better option would be to change `simple_uart_read` to take a timeout, and it is guaranteed to finish by then. This is already essentially done internally, but it's not user configurable.

That wouldn't guarantee that you would get `n` bytes, but you could obviously call the function again if necessary. The reality is that due to hardware flow control and other things, sometimes there is no way to guarantee that you can read/write anything at all.

I think the best thing would be to change it to:
`int simple_uart_read(struct simple_uart *sc, void *buffer, int max_len, int timeout_ms)`
Where a negative timeout would indicate that we will wait forever to get at least 1 byte.

**Comment by andkae** [comment]
Yeah, sounds reasonable.But What with the legacy compatibility, what should the default value for this new function? Another question, applies the ```timeout``` to one byte, means whenever a byte is recieved the timeout is resetted, or to the whole chunk of data?

**Comment by AndreRenaud** [comment]
Given the way this library is used (directly with minimal dependencies, static linking etc...) I'm not too concerned about maintaining compatibility - there aren't enough users to really hamper ourselves with it. So I don't think we need to have a default value - it will always be specified by the caller.

The timeout should be across the entire read - so not reset after each byte. Basically, if that amount of time has received, and we've received <= max_len bytes, then we exit with success. If the timeout expires and we haven't received any bytes, then we exit with a timeout error.

**Comment by andkae** [comment]
For my use case it worked with:

```c
/* read until number of required bytes are captured */
while ( r < len ) {
	r = r + ((uint32_t) simple_uart_read(self->uart, data+r, (int) (len-r)));
}
```

Therefore from my site no need for an Timeout, i would close the Issue.
